<?php 
$title = 'Event Summary Report - ' . $event['name'];
require __DIR__ . '/../layout/header.php'; 
?>

<div class="d-flex justify-content-between align-items-center mb-4">
    <h1><i class="fas fa-file-alt"></i> Event Summary Report</h1>
    <div>
        <button onclick="window.print()" class="btn btn-info">
            <i class="fas fa-print"></i> Print
        </button>
        <a href="/tabulation/events/<?= $event['id'] ?>/reports" class="btn btn-secondary">Back</a>
    </div>
</div>

<div class="card mb-4">
    <div class="card-body">
        <h3><?= htmlspecialchars($event['name']) ?></h3>
        <div class="row">
            <div class="col-md-6">
                <p class="mb-1">
                    <strong>Event Type:</strong> <?= htmlspecialchars($event['event_type']) ?><br>
                    <strong>Venue:</strong> <?= htmlspecialchars($event['venue'] ?: '-') ?><br>
                    <strong>Date:</strong> <?= htmlspecialchars($event['event_date']) ?><br>
                    <?php if ($event['start_time']): ?>
                        <strong>Start Time:</strong> <?= date('h:i A', strtotime($event['start_time'])) ?><br>
                    <?php endif; ?>
                    <?php if ($event['end_time']): ?>
                        <strong>End Time:</strong> <?= date('h:i A', strtotime($event['end_time'])) ?><br>
                    <?php endif; ?>
                    <strong>Status:</strong> 
                    <span class="badge bg-<?= $event['status'] === 'Ongoing' ? 'success' : ($event['status'] === 'Finished' ? 'secondary' : 'warning') ?>">
                        <?= htmlspecialchars($event['status']) ?>
                    </span>
                </p>
            </div>
            <div class="col-md-6">
                <h6>Statistics</h6>
                <p class="mb-1">
                    <strong>Total Judges:</strong> <?= $stats['total_judges'] ?><br>
                    <strong>Total Contestants:</strong> <?= $stats['total_contestants'] ?><br>
                    <strong>Total Levels:</strong> <?= $stats['total_levels'] ?><br>
                    <strong>Total Rounds:</strong> <?= $stats['total_rounds'] ?>
                </p>
            </div>
        </div>
    </div>
</div>

<?php if (!empty($winners)): ?>
    <div class="card">
        <div class="card-header bg-warning text-dark">
            <h5 class="mb-0"><i class="fas fa-trophy"></i> Top 10 Winners</h5>
        </div>
        <div class="card-body p-0">
            <div class="table-responsive">
                <table class="table table-bordered table-hover mb-0">
                    <thead class="thead-light">
                        <tr>
                            <th class="text-center">Rank</th>
                            <th>Contestant #</th>
                            <th>Name</th>
                            <th class="text-center">Total Score</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($winners as $winner): ?>
                        <tr class="<?= $winner['rank'] <= 3 ? 'table-warning' : '' ?>">
                            <td class="text-center">
                                <?php if ($winner['rank'] == 1): ?>
                                    <h3 class="mb-0"><span class="badge bg-warning text-dark"><i class="fas fa-trophy"></i> Winner</span></h3>
                                <?php elseif ($winner['rank'] == 2): ?>
                                    <h4 class="mb-0"><span class="badge bg-secondary">1st Runner-up</span></h4>
                                <?php elseif ($winner['rank'] == 3): ?>
                                    <h4 class="mb-0"><span class="badge" style="background-color: #CD7F32; color: white;">2nd Runner-up</span></h4>
                                <?php else: ?>
                                    <h5 class="mb-0"><?= $winner['rank'] ?></h5>
                                <?php endif; ?>
                            </td>
                            <td><strong>#<?= htmlspecialchars($winner['contestant_number']) ?></strong></td>
                            <td><strong><?= htmlspecialchars($winner['name']) ?></strong></td>
                            <td class="text-center"><strong><?= number_format($winner['total_score'], 3) ?></strong></td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
<?php else: ?>
    <div class="alert alert-info">
        Final results not yet available.
    </div>
<?php endif; ?>

<div class="card mt-4">
    <div class="card-body">
        <p class="mb-0 text-muted">
            <strong>Report Generated:</strong> <?= date('F d, Y h:i A') ?><br>
            <strong>Generated By:</strong> <?= htmlspecialchars(Session::get('full_name')) ?>
        </p>
    </div>
</div>

<style>
@media print {
    .btn {
        display: none;
    }
}
</style>

<?php require __DIR__ . '/../layout/footer.php'; ?>
