-- Create report_deductions table for round/level/final aggregate deductions
CREATE TABLE IF NOT EXISTS `report_deductions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `event_id` INT(11) NOT NULL,
  `scope_type` ENUM('round', 'level', 'final') NOT NULL,
  `scope_id` INT(11) NOT NULL DEFAULT 0,
  `contestant_id` INT(11) NOT NULL,
  `deduction` DECIMAL(10,3) NOT NULL DEFAULT 0.000,
  `reason` TEXT NULL,
  `status` ENUM('requested', 'granted', 'denied') NOT NULL DEFAULT 'requested',
  `requested_by` INT(11) NULL,
  `requested_at` TIMESTAMP NULL,
  `responded_by` INT(11) NULL,
  `responded_at` TIMESTAMP NULL,
  `created_by` INT(11) NULL,
  `updated_by` INT(11) NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_report_deduction` (`event_id`, `scope_type`, `scope_id`, `contestant_id`),
  INDEX `idx_event_scope` (`event_id`, `scope_type`, `scope_id`),
  INDEX `idx_status` (`status`),
  INDEX `idx_contestant_id` (`contestant_id`),
  FOREIGN KEY (`event_id`) REFERENCES `events`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`contestant_id`) REFERENCES `contestants`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`requested_by`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`responded_by`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON DELETE SET NULL,
  FOREIGN KEY (`updated_by`) REFERENCES `users`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
